spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easynews?autoReconnect=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ckdwls6504
    password: 3044
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 608577946136-ufg9uht86rqc04er2eagk4583mtaq6sm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email